SceptrDocumentationTool/SceptrDocumentationTool/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientSupplierMapper.Models;

namespace SceptrDocumentationTool.Controllers
{   
    public class SuppliersController : Controller
    {
        private ClientSupplierContext context = new ClientSupplierContext();

        //
        // GET: /Suppliers/

        public ViewResult Index()
        {
            return View(context.Suppliers.Include(supplier => supplier.Clients).ToList());
        }

        //
        // GET: /Suppliers/Details/5

        public ViewResult Details(int id)
        {
            Supplier supplier = context.Suppliers.Single(x => x.ID == id);
            return View(supplier);
        }

        //
        // GET: /Suppliers/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /Suppliers/Create

        [HttpPost]
        public ActionResult Create(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                context.Suppliers.Add(supplier);
                context.SaveChanges();
                return RedirectToAction("Index");  
            }

            return View(supplier);
        }
        
        //
        // GET: /Suppliers/Edit/5
 
        public ActionResult Edit(int id)
        {
            Supplier supplier = context.Suppliers.Single(x => x.ID == id);
            return View(supplier);
        }

        //
        // POST: /Suppliers/Edit/5

        [HttpPost]
        public ActionResult Edit(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                context.Entry(supplier).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(supplier);
        }

        //
        // GET: /Suppliers/Delete/5
 
        public ActionResult Delete(int id)
        {
            Supplier supplier = context.Suppliers.Single(x => x.ID == id);
            return View(supplier);
        }

        //
        // POST: /Suppliers/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplier supplier = context.Suppliers.Single(x => x.ID == id);
            context.Suppliers.Remove(supplier);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
        //public ActionResult Search()
        //{
        //    ViewBag.Message = "Supplier Documentation Tool";

        //    return View();
        //}
        //[ActionName("SearchBySupplier")]
        //public ActionResult SearchBySupplier(string supplierName)
        //{
        //    var supplierList = new List<string>();

        //    var suppliers = from s in context.Suppliers select s.Name;

        //    ViewBag.supplierName = new SelectList(supplierList);

        //    var reqdResult = from t in context.ClientSupplierMaps select t;

        //    if (!String.IsNullOrEmpty(supplierName))
        //    {
        //        int suppId = -1;
        //        var supplier = from s in context.Suppliers where s.Name == supplierName select s;
        //        //supplier = supplier.Where(s => s.Name.Contains(supplierName));
        //        //var result = new List<ClientSupplierMap>();
        //        foreach (var row in supplier)
        //        {
        //            suppId = row.ID;
        //        }
        //        if (suppId != -1)
        //        {
        //            var clients = from rec in context.ClientSupplierMaps where rec.Supplier.Name.Contains(supplierName) select rec;//w/o sup name
        //            return View(clients);
        //        }
        //    }
        //    return View(reqdResult);
        //}
    }
}

SceptrDocumentationTool/SceptrDocumentationTool/Views/Suppliers/Create.cshtml
@model ClientSupplierMapper.Models.Supplier

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Supplier</legend>

		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SceptrDocumentationTool/SceptrDocumentationTool/Views/Suppliers/Delete.cshtml
@model ClientSupplierMapper.Models.Supplier

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Supplier</legend>

    <div class="display-label">Name</div>
    <div class="display-field">@Model.Name</div>

    <div class="display-label">Clients</div>
    <div class="display-field">@(Model.Clients == null ? "None" : Model.Clients.Count.ToString())</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

SceptrDocumentationTool/SceptrDocumentationTool/Views/Suppliers/Details.cshtml
@model ClientSupplierMapper.Models.Supplier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Supplier</legend>

    <div class="display-label">Name</div>
    <div class="display-field">@Model.Name</div>

    <div class="display-label">Clients</div>
    <div class="display-field">@(Model.Clients == null ? "None" : Model.Clients.Count.ToString())</div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SceptrDocumentationTool/SceptrDocumentationTool/Views/Suppliers/Edit.cshtml
@model ClientSupplierMapper.Models.Supplier

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Supplier</legend>

        @Html.HiddenFor(model => model.ID)
		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SceptrDocumentationTool/SceptrDocumentationTool/Views/Suppliers/Index.cshtml
@model IEnumerable<ClientSupplierMapper.Models.Supplier>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th></th>
        <th>
            Name
        </th>
        <th>
            Clients
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
        <td>
			@item.Name
        </td>
        <td>
			@(item.Clients == null ? "None" : item.Clients.Count.ToString())
        </td>
    </tr>
}
<div>
    @Html.ActionLink("Search By Supplier", "Search")
</div>
</table>

SceptrDocumentationTool/SceptrDocumentationTool/Views/Suppliers/Search.cshtml
@model ClientSupplierMapper.Models.Supplier

@{
    ViewBag.Title = "Search By Supplier";
}
<div class="display-field">
    <p>Supplier's Name</p>
</div>

    @using (Html.BeginForm("SearchBySupplier", "Suppliers", FormMethod.Get))
    {
        @Html.ValidationSummary(false)
            <fieldset>  
                <legend>Supplier</legend>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Name)
                </div>
                <p>
                    <input type="submit" value="Search" />
                </p>
              </fieldset>
    }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SceptrDocumentationTool/SceptrDocumentationTool/Views/Suppliers/SearchBySupplier.cshtml
@model IEnumerable<ClientSupplierMapper.Models.ClientSupplierMap>

@{
    ViewBag.Title = "SearchBySupplier";
}

<h2>SearchBySupplier</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Supplier ID
        </th>
        <th>
            Supplier Name
        </th>
        <th>
            Product Type
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Supplier.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Supplier.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

SceptrDocumentationTool/SceptrDocumentationTool/Views/Suppliers/_CreateOrEdit.cshtml
@model ClientSupplierMapper.Models.Supplier

@* This partial view defines form fields that will appear when creating and editing entities *@

<div class="editor-label">
    @Html.LabelFor(model => model.Name)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.Name)
    @Html.ValidationMessageFor(model => model.Name)
</div>