SceptrDocumentationTool/SceptrDocumentationTool/Controllers/ClientSupplierMapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientSupplierMapper.Models;

namespace SceptrDocumentationTool.Controllers
{   
    public class ClientSupplierMapsController : Controller
    {
        private ClientSupplierContext context = new ClientSupplierContext();

        //
        // GET: /ClientSupplierMaps/

        public ViewResult Index()
        {
            return View(context.ClientSupplierMaps.Include(clientsuppliermap => clientsuppliermap.Client).Include(clientsuppliermap => clientsuppliermap.Supplier).Include(clientsuppliermap => clientsuppliermap.Product).ToList());
        }

        //
        // GET: /ClientSupplierMaps/Details/5

        public ViewResult Details(int id)
        {
            ClientSupplierMap clientsuppliermap = context.ClientSupplierMaps.Single(x => x.Id == id);
            return View(clientsuppliermap);
        }

        //
        // GET: /ClientSupplierMaps/Create

        public ActionResult Create()
        {
            ViewBag.PossibleClients = context.Clients;
            ViewBag.PossibleSuppliers = context.Suppliers;
            ViewBag.PossibleProducts = context.Products;
            return View();
        } 

        //
        // POST: /ClientSupplierMaps/Create

        [HttpPost]
        public ActionResult Create(ClientSupplierMap clientsuppliermap)
        {
            if (ModelState.IsValid)
            {
                context.ClientSupplierMaps.Add(clientsuppliermap);
                context.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.PossibleClients = context.Clients;
            ViewBag.PossibleSuppliers = context.Suppliers;
            ViewBag.PossibleProducts = context.Products;
            return View(clientsuppliermap);
        }
        
        //
        // GET: /ClientSupplierMaps/Edit/5
 
        public ActionResult Edit(int id)
        {
            ClientSupplierMap clientsuppliermap = context.ClientSupplierMaps.Single(x => x.Id == id);
            ViewBag.PossibleClients = context.Clients;
            ViewBag.PossibleSuppliers = context.Suppliers;
            ViewBag.PossibleProducts = context.Products;
            return View(clientsuppliermap);
        }

        //
        // POST: /ClientSupplierMaps/Edit/5

        [HttpPost]
        public ActionResult Edit(ClientSupplierMap clientsuppliermap)
        {
            if (ModelState.IsValid)
            {
                context.Entry(clientsuppliermap).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PossibleClients = context.Clients;
            ViewBag.PossibleSuppliers = context.Suppliers;
            ViewBag.PossibleProducts = context.Products;
            return View(clientsuppliermap);
        }

        //
        // GET: /ClientSupplierMaps/Delete/5
 
        public ActionResult Delete(int id)
        {
            ClientSupplierMap clientsuppliermap = context.ClientSupplierMaps.Single(x => x.Id == id);
            return View(clientsuppliermap);
        }

        //
        // POST: /ClientSupplierMaps/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ClientSupplierMap clientsuppliermap = context.ClientSupplierMaps.Single(x => x.Id == id);
            context.ClientSupplierMaps.Remove(clientsuppliermap);
            context.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult Search()
        {
            ViewBag.Message = "Supplier Documentation Tool";

            return View();
        }

        [ActionName("SearchBySupplier")]
        public ActionResult SearchBySupplier(string Name)
        {
            //string supplierName = supplier1.Name;
            var supplierList = new List<string>();

            var suppliers = from s in context.Suppliers select s.Name;

            ViewBag.supplierName = new SelectList(supplierList);

            var reqdResult = from t in context.ClientSupplierMaps select t;

            if (!String.IsNullOrEmpty(Name))
            {
                int suppId = -1;
                var supplier = from s in context.Suppliers where s.Name == Name select s;
                foreach (var row in supplier)
                {
                    suppId = row.ID;
                }
                if (suppId != -1)
                {
                    var clients = from rec in context.ClientSupplierMaps where rec.Supplier.Name.Contains(Name) select rec;//w/o sup name
                    return View(clients);
                }
            }
            return View(reqdResult);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SceptrDocumentationTool/SceptrDocumentationTool/Views/ClientSupplierMaps/Create.cshtml
@model ClientSupplierMapper.Models.ClientSupplierMap

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>ClientSupplierMap</legend>

		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SceptrDocumentationTool/SceptrDocumentationTool/Views/ClientSupplierMaps/Delete.cshtml
@model ClientSupplierMapper.Models.ClientSupplierMap

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>ClientSupplierMap</legend>

    <div class="display-label">Client</div>
    <div class="display-field">@(Model.Client == null ? "None" : Model.Client.Name)</div>

    <div class="display-label">Supplier</div>
    <div class="display-field">@(Model.Supplier == null ? "None" : Model.Supplier.Name)</div>

    <div class="display-label">Product</div>
    <div class="display-field">@(Model.Product == null ? "None" : Model.Product.Name)</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

SceptrDocumentationTool/SceptrDocumentationTool/Views/ClientSupplierMaps/Details.cshtml
@model ClientSupplierMapper.Models.ClientSupplierMap

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>ClientSupplierMap</legend>

    <div class="display-label">Client</div>
    <div class="display-field">@(Model.Client == null ? "None" : Model.Client.Name)</div>

    <div class="display-label">Supplier</div>
    <div class="display-field">@(Model.Supplier == null ? "None" : Model.Supplier.Name)</div>

    <div class="display-label">Product</div>
    <div class="display-field">@(Model.Product == null ? "None" : Model.Product.Name)</div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SceptrDocumentationTool/SceptrDocumentationTool/Views/ClientSupplierMaps/Edit.cshtml
@model ClientSupplierMapper.Models.ClientSupplierMap

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>ClientSupplierMap</legend>

        @Html.HiddenFor(model => model.Id)
		@Html.Partial("_CreateOrEdit", Model)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SceptrDocumentationTool/SceptrDocumentationTool/Views/ClientSupplierMaps/Index.cshtml
@model IEnumerable<ClientSupplierMapper.Models.ClientSupplierMap>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th></th>
        <th>
            Client
        </th>
        <th>
            Supplier
        </th>
        <th>
            Product
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
        <td>
			@(item.Client == null ? "None" : item.Client.Name)
        </td>
        <td>
			@(item.Supplier == null ? "None" : item.Supplier.Name)
        </td>
        <td>
			@(item.Product == null ? "None" : item.Product.Name)
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Search By Supplier", "Search")
</div>

SceptrDocumentationTool/SceptrDocumentationTool/Views/ClientSupplierMaps/Search.cshtml
@model ClientSupplierMapper.Models.Supplier

@{
    ViewBag.Title = "Search By Supplier";
}
<div class="display-field">
    <p>Supplier's Name</p>
</div>

    @using (Html.BeginForm("SearchBySupplier", "ClientSupplierMaps", FormMethod.Get))
    {
        @Html.ValidationSummary(false)
            <fieldset>  
                <legend>Supplier</legend>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Name)
                </div>
                <p>
                    <input type="submit" value="Search" />
                </p>
              </fieldset>
    }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SceptrDocumentationTool/SceptrDocumentationTool/Views/ClientSupplierMaps/SearchBySupplier.cshtml
@model IEnumerable<ClientSupplierMapper.Models.ClientSupplierMap>

@{
    ViewBag.Title = "SearchBySupplier";
}

<h2>SearchBySupplier</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            <h6>Supplier ID</h6>
            
            @*@Html.DisplayNameFor(model => model.SupplierId)*@
        </th>
        <th>
            <h6>Supplier Name</h6>
            @*@Html.DisplayNameFor(model => model.Supplier.Name)*@
        </th>
        <th>
            <h6>Product Type</h6>
            @*@Html.DisplayNameFor(model => model.Product.Name)*@
        </th>
        
        <th>
            <h6>Client Name</h6>
            @*@Html.DisplayNameFor(model => model.Product.Name)*@
        </th>


        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SupplierId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Supplier.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Client.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

SceptrDocumentationTool/SceptrDocumentationTool/Views/ClientSupplierMaps/_CreateOrEdit.cshtml
@model ClientSupplierMapper.Models.ClientSupplierMap

@* This partial view defines form fields that will appear when creating and editing entities *@

<div class="editor-label">
    Client
</div>
<div class="editor-field">
    @Html.DropDownListFor(model => model.ClientId, ((IEnumerable<ClientSupplierMapper.Models.Client>)ViewBag.PossibleClients).Select(option => new SelectListItem {
        Text = (option == null ? "None" : option.Name), 
        Value = option.ID.ToString(),
        Selected = (Model != null) && (option.ID == Model.ClientId)
    }), "Choose...")
    @Html.ValidationMessageFor(model => model.ClientId)
</div>
<div class="editor-label">
    Supplier
</div>
<div class="editor-field">
    @Html.DropDownListFor(model => model.SupplierId, ((IEnumerable<ClientSupplierMapper.Models.Supplier>)ViewBag.PossibleSuppliers).Select(option => new SelectListItem {
        Text = (option == null ? "None" : option.Name), 
        Value = option.ID.ToString(),
        Selected = (Model != null) && (option.ID == Model.SupplierId)
    }), "Choose...")
    @Html.ValidationMessageFor(model => model.SupplierId)
</div>
<div class="editor-label">
    Product
</div>
<div class="editor-field">
    @Html.DropDownListFor(model => model.ProductId, ((IEnumerable<ClientSupplierMapper.Models.Product>)ViewBag.PossibleProducts).Select(option => new SelectListItem {
        Text = (option == null ? "None" : option.Name), 
        Value = option.ID.ToString(),
        Selected = (Model != null) && (option.ID == Model.ProductId)
    }), "Choose...")
    @Html.ValidationMessageFor(model => model.ProductId)
</div>